config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  resources :places, only: :index
  resources :events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :place
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :events, dependent: :destroy

  validates :place_name, :address, :latitude, :longitude, :city, :country, :zip_code, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def new
    @event = Event.new

  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to events_path
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  private

  def event_params
    params.require(:event).permit(:event_name, :start_time, :end_time, :cover, :place_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
    @places = Place.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/_event_form.html.erb
<div class="container">
  <div class="row justify_content-center">
    <div class="col-sm-12 col-md-6">
      <%= simple_form_for @event do |f| %>
        <%= f.input :event_name %>
        <%= f.input :start_time %>
        <%= f.input :end_time %>
        <%= f.input :cover %>
        <%= f.association :place %>
        <%= f.submit class: "btn btn-outline-primary float-rigth" %>
      <% end %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="container">
  <h1 class="mt-4">Events#index</h1>
  <p>Find me in app/views/events/index.html.erb</p>
  <% @events.each do |event| %>
    <%= link_to event_path(event) do %>
      <div class="card">
        <div class="card-image">
          <%= image_tag event.cover, width: 160, height: 90  %>
          <%= event.event_name %>
        </div>
      </div>
    <% end %>
  <% end %>
  <%= link_to 'Create a New Event', new_event_path, class: 'mt-4 float-right btn btn-outline-primary' %>
</div>

app/views/events/new.html.erb
<div class="container mt-4">
  <h1>Events#new</h1>
  <p>Find me in app/views/events/new.html.erb</p>
  <%= render 'event_form' %>
</div>

app/views/events/show.html.erb
<div class="container">
  <h1 class="mt-4">Events#show</h1>
  <p>Find me in app/views/events/show.html.erb</p>
  <div class="card">
    <div class="card-image">
      <%= image_tag @event.cover, width: 640, height: 360  %>
      <%= @event.event_name %>
    </div>
  </div>
  <%= link_to 'Back', events_path, class: 'mt-4 float-right btn btn-outline-primary' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <h1 class="mt-4">Pages#home</h1>
  <p>Find me in app/views/pages/home.html.erb</p>

  <%= link_to 'Create a New Event', new_event_path, class: 'btn btn-outline-primary' %>
</div>

app/views/places/index.html.erb
<h1>Places#index</h1>
<p>Find me in app/views/places/index.html.erb</p>

<% @places.all.each do |place| %>
  <div class="card">
    <%= place.place_name %> | <%= place.latitude %> | <%= place.longitude %>
    | <%= place.address %> | <%= place.city %> | <%= place.country %> | <%= place.zip_code %> |
  </div>
<% end %>